export const ADD_FOLDER = "ADD_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const ADD_ALBUM_TO_FOLDER = "ADD_ALBUM_TO_FOLDER";
export const REMOVE_ALBUM_FROM_FOLDER = "REMOVE_ALBUM_FROM_FOLDER";

export const FETCH_ALBUMS = "FETCH_ALBUMS";

export const GET_TOKEN = "GET_TOKEN";

export const ERROR = "ERROR";